# Generated by Django 4.1.2 on 2022-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eslahi_murobbi_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
