# Generated by Django 4.1.2 on 2023-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='previous_exam_institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_institution_session',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
