# Generated by Django 4.1.2 on 2022-10-29 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_eslahi_murobbi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_breakfast', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_snacks', models.BooleanField(default=False)),
                ('is_dinner', models.BooleanField(default=False)),
                ('meal_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meail_info_user', to=settings.AUTH_USER_MODEL)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_info_madrashas', to='accounts.madrasha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_info_student', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'meal_date')},
            },
        ),
    ]
