# Generated by Django 4.1.2 on 2022-11-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mealinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
