# Generated by Django 4.1.2 on 2022-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_academic_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
