# Generated by Django 4.1.2 on 2022-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='organization_with_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
