# Generated by Django 4.1.2 on 2022-11-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_parent_organization_with_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
