# Generated by Django 4.1.2 on 2022-11-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_parent_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_fees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees_info', to='students.academicfess'),
        ),
    ]
