# Generated by Django 4.1.2 on 2022-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_academic_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
