# Generated by Django 4.1.2 on 2022-11-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_academic_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(choices=[('null', ''), ('teacher', 'Teacher'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('other', 'Other')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_exam_name',
            field=models.CharField(blank=True, choices=[('null', ''), ('befak', 'Befak'), ('haya', 'Haya')], default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, choices=[('null', ''), ('teacher', 'Teacher'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('other', 'Other')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, choices=[('null', ''), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunty', 'Aunty'), ('cousin', 'Cousin')], default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_contact_person_relation',
            field=models.CharField(blank=True, choices=[('null', ''), ('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunty', 'Aunty'), ('cousin', 'Cousin')], max_length=20, null=True),
        ),
    ]
