# Generated by Django 4.1.2 on 2022-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_parent_occupation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_nid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
