# Generated by Django 4.1.2 on 2022-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_parent_parent_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(choices=[('null', ''), ('teacher', 'Teacher'), ('alim', 'Alim'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('govt-employee', 'Govt. employee'), ('house-wife', 'House Wife'), ('other', 'Other')], default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='board_exam_name',
            field=models.CharField(blank=True, choices=[('null', ''), ('haya', 'Al Haiatul Ulya'), ('befak_arabia', 'Befaq(Arabia)'), ('befak_dinia', 'Befaq(Dinia)'), ('tanjimul madares', 'Tanjimul Madares')], default='null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, choices=[('null', ''), ('teacher', 'Teacher'), ('alim', 'Alim'), ('farmer', 'Farmer'), ('doctor', 'Doctor'), ('police', 'Police'), ('businessman', 'Businessman'), ('govt-employee', 'Govt. employee'), ('non-govt-employee', 'Non govt. employee'), ('govt-employee', 'Govt. employee'), ('house-wife', 'House Wife'), ('other', 'Other')], default='null', max_length=20, null=True),
        ),
    ]
