# Generated by Django 4.1.2 on 2022-12-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_fessinfo_madrasha_fessinfo_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boarding_feee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_tution_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
