# Generated by Django 4.1.2 on 2022-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_boarding_feee_student_monthly_tution_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
