# Generated by Django 4.1.2 on 2022-12-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_updated_cat_studentincome_updated_at_and_more'),
        ('settingapp', '0016_alter_fees_options_fees_category_fees_is_first_term_and_more'),
        ('students', '0015_student_boarding_feee_student_monthly_tution_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fessinfo',
            old_name='fee_name',
            new_name='fees_type',
        ),
        migrations.RemoveField(
            model_name='fessinfo',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fessinfo',
            name='for_exam_term',
        ),
        migrations.RemoveField(
            model_name='fessinfo',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='fessinfo',
            name='current_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fessinfo',
            name='fees_type_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examter_fees', to='settingapp.fees'),
        ),
        migrations.AddField(
            model_name='fessinfo',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fessinfo',
            name='student_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.studentincome'),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
