# Generated by Django 4.1.2 on 2022-12-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_rename_fee_name_fessinfo_fees_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boarding_fee_active_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_boarding_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_transport_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_tution_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_fee_active_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tution_fee_active_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
