# Generated by Django 4.1.2 on 2022-12-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_admission_fee_student_transport_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fessinfo',
            old_name='fee_name',
            new_name='fees_type',
        ),
        migrations.RenameField(
            model_name='fessinfo',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='fessinfo',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='fessinfo',
            name='current_fee',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
