# Generated by Django 4.1.2 on 2022-12-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_amount_studentincome_total_amount_and_more'),
        ('students', '0017_rename_fee_name_fessinfo_fees_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fessinfo',
            name='student_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.studentincome'),
        ),
        migrations.AlterField(
            model_name='fessinfo',
            name='current_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
