# Generated by Django 4.1.2 on 2022-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_boarding_fee_active_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fessinfo',
            name='fees_type_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
