# Generated by Django 4.1.2 on 2022-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_rename_for_exam_term_fessinfo_fees_type_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fessinfo',
            name='paid_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
