# Generated by Django 4.1.2 on 2023-01-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_slug_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
