# Generated by Django 4.1.2 on 2022-12-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0018_alter_fees_options_alter_fees_unique_together_and_more'),
        ('students', '0020_alter_fessinfo_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fessinfo',
            name='fees_type_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examter_fees', to='settingapp.fees'),
        ),
    ]
