# Generated by Django 4.1.2 on 2022-11-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0009_alter_student_academic_fees'),
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhabarDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_breakfast', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_dinner', models.BooleanField(default=False)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khabar_distribution_madrasha', to='accounts.madrasha')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khabar_distribution_student', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bazar_item_name', models.CharField(max_length=250)),
                ('quantity', models.CharField(max_length=250)),
                ('measurement', models.CharField(choices=[('kg', 'Kg'), ('litre', 'Litre'), ('gm', 'Gm')], default='Kg', max_length=10)),
                ('amount', models.CharField(max_length=250)),
                ('consumption', models.CharField(max_length=250)),
                ('total_stock', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField()),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazarItem_madrasha', to='accounts.madrasha')),
            ],
        ),
    ]
