# Generated by Django 4.1.2 on 2023-01-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('boarding', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khabardistribution',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='khabar_distribution_student', to='students.student'),
        ),
        migrations.AddField(
            model_name='dailybazar',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bazarItem_madrasha', to='accounts.madrasha'),
        ),
    ]
