# Generated by Django 4.1.2 on 2022-11-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('settingapp', '0011_room_floor'),
        ('students', '0004_alter_student_academic_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_seats', to='settingapp.building')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_seat_booking', to='accounts.madrasha')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_seats', to='settingapp.room')),
                ('seat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_seat', to='settingapp.seat')),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_seat_dist', to='students.student')),
            ],
        ),
    ]
