# Generated by Django 4.1.2 on 2022-11-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0011_room_floor'),
        ('darul_ekama', '0002_nigranitable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nigranitable',
            name='room',
        ),
        migrations.AddField(
            model_name='nigranitable',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, related_name='room_nigran', to='settingapp.room'),
        ),
    ]
