# Generated by Django 4.1.2 on 2022-11-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darul_ekama', '0003_remove_nigranitable_room_nigranitable_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nigranitable',
            name='floor',
            field=models.CharField(max_length=20),
        ),
    ]
