# Generated by Django 4.1.2 on 2022-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0012_building_total_floor_building_total_room'),
        ('darul_ekama', '0004_alter_nigranitable_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nigranitable',
            name='room',
            field=models.ManyToManyField(blank=True, related_name='room_nigran', to='settingapp.room'),
        ),
    ]
