# Generated by Django 4.1.2 on 2023-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
