# Generated by Django 4.1.2 on 2023-01-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madrasha',
            options={},
        ),
    ]
