# Generated by Django 4.1.2 on 2022-12-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_experience_alter_teacher_skill_teacher_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birth_certificate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
