# Generated by Django 4.1.2 on 2022-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_birth_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_home',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
