# Generated by Django 4.1.2 on 2022-11-01 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermanentMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('madrasha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.madrasha')),
            ],
            options={
                'ordering': ['member_name'],
                'unique_together': {('phone_number', 'madrasha')},
            },
        ),
        migrations.CreateModel(
            name='OtherMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('madrasha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.madrasha')),
            ],
            options={
                'ordering': ['member_name'],
                'unique_together': {('phone_number', 'madrasha')},
            },
        ),
    ]
