# Generated by Django 4.1.2 on 2022-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_permanentmembers_othermembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentmembers',
            name='is_monthly_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permanentmembers',
            name='is_yearly_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permanentmembers',
            name='monthly_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentmembers',
            name='yearly_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
