# Generated by Django 4.1.2 on 2022-12-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_permanentmembers_is_monthly_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permanentmembers',
            name='monthly_activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentmembers',
            name='yearly_activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
