# Generated by Django 4.1.2 on 2022-12-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_studentincome_to_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentincome',
            old_name='updated_cat',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='category',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='for_month',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='for_months',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='studentincome',
            name='to_month',
        ),
        migrations.AddField(
            model_name='studentincome',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentincome',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentincome',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
