# Generated by Django 4.1.2 on 2022-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_amount_studentincome_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentincome',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
