# Generated by Django 4.1.2 on 2022-12-28 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_permanentmembers_monthly_activation_date_and_more'),
        ('accounts', '0002_alter_customuser_email'),
        ('transactions', '0004_otherincome_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherincome',
            old_name='for_months',
            new_name='member_type',
        ),
        migrations.RemoveField(
            model_name='otherincome',
            name='for_month',
        ),
        migrations.AddField(
            model_name='otherincome',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='amount',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_others', to='transactions.incomecategory'),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='donar_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='madrasha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='other_incomes', to='accounts.madrasha'),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member_id', to='committees.permanentmembers'),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='paid_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories_others', to='transactions.incomesubcategory'),
        ),
    ]
