# Generated by Django 4.1.2 on 2022-12-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_for_months_otherincome_member_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allexpense',
            name='for_month',
        ),
        migrations.RemoveField(
            model_name='allexpense',
            name='for_months',
        ),
        migrations.AlterField(
            model_name='otherincome',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
