# Generated by Django 4.1.2 on 2022-12-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0003_bookdistributetoteacher_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallduty',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hallduty',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hallduty',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
