# Generated by Django 4.1.2 on 2022-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talimats', '0004_hallduty_date_hallduty_end_time_hallduty_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallduty',
            name='duty_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
