# Generated by Django 4.1.2 on 2022-10-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_designations', to='settingapp.department'),
        ),
    ]
