# Generated by Django 4.1.2 on 2023-01-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingapp', '0001_initial'),
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_seat', to='students.student'),
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_rooms', to='settingapp.building'),
        ),
        migrations.AddField(
            model_name='room',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_rooms', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='madrashagroup',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_madrasha_group', to='settingapp.department'),
        ),
        migrations.AddField(
            model_name='madrashagroup',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_groups', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='madrashagroup',
            name='madrasha_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_madrasha_group', to='settingapp.madrashaclasses'),
        ),
        migrations.AddField(
            model_name='madrashaclasses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_classes', to='settingapp.department'),
        ),
        migrations.AddField(
            model_name='madrashaclasses',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_classes', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='khabartakinggroup',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_khabar_dist_group', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='feescategory',
            name='madrash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_fees_category', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='fees',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingapp.feescategory'),
        ),
        migrations.AddField(
            model_name='fees',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_fees', to='settingapp.department'),
        ),
        migrations.AddField(
            model_name='fees',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_fees', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='fees',
            name='madrasha_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_fees', to='settingapp.madrashaclasses'),
        ),
        migrations.AddField(
            model_name='examrules',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_exam_rules', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_designations', to='settingapp.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_designations', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='department',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_departments', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='building',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_buildings', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='books',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_books', to='settingapp.department'),
        ),
        migrations.AddField(
            model_name='books',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_books', to='accounts.madrasha'),
        ),
        migrations.AddField(
            model_name='books',
            name='madrasha_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_books', to='settingapp.madrashaclasses'),
        ),
        migrations.AddField(
            model_name='admitcardinfo',
            name='madrasha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_admit_info', to='accounts.madrasha'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='madrashagroup',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='madrashaclasses',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('term_name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'madrasha')},
        ),
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('name', 'madrasha')},
        ),
    ]
