# Generated by Django 4.1.2 on 2022-10-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0002_designation_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='actual_year',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
