# Generated by Django 4.1.2 on 2022-10-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0003_session_actual_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='department',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='madrashaclasses',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='madrashagroup',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='session',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='slug',
        ),
    ]
