# Generated by Django 4.1.2 on 2022-10-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('settingapp', '0004_remove_books_slug_remove_department_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talimat_name', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=300)),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_admit_info', to='accounts.madrasha')),
            ],
        ),
    ]
