# Generated by Django 4.1.2 on 2022-11-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0007_seats_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
