# Generated by Django 4.1.2 on 2022-11-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mealinfo'),
        ('settingapp', '0009_room_seat_remove_seats_madrasha_delete_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_seat', to='students.student'),
        ),
    ]
