# Generated by Django 4.1.2 on 2022-11-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0010_seat_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
