# Generated by Django 4.1.2 on 2022-11-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0011_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='total_floor',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='total_room',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
