# Generated by Django 4.1.2 on 2022-11-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
        ('settingapp', '0012_building_total_floor_building_total_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhabarTakingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrasha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_khabar_dist_group', to='accounts.madrasha')),
            ],
        ),
    ]
