# Generated by Django 4.1.2 on 2022-12-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0013_khabartakinggroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fees',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fees',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingapp.feescategory'),
        ),
    ]
