# Generated by Django 4.1.2 on 2022-12-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0014_feescategory_alter_fees_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fees',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='fees',
            name='category',
        ),
    ]
