# Generated by Django 4.1.2 on 2022-12-18 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
        ('settingapp', '0015_alter_fees_options_remove_fees_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingapp.feescategory'),
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('name', 'madrasha')},
        ),
    ]
