# Generated by Django 4.1.2 on 2022-12-18 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
        ('settingapp', '0016_fees_category_alter_fees_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feescategory',
            name='madrash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='madrasha_fees_category', to='accounts.madrasha'),
        ),
    ]
