# Generated by Django 4.1.2 on 2022-12-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingapp', '0016_alter_fees_options_fees_category_fees_is_first_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='examination_fee_active_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
