# Generated by Django 4.1.2 on 2022-12-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
        ('settingapp', '0017_feescategory_madrash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fees',
            options={'ordering': ['term_name']},
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fees',
            name='is_first_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fees',
            name='is_second_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fees',
            name='is_third_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fees',
            name='term_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fees',
            unique_together={('term_name', 'madrasha')},
        ),
        migrations.RemoveField(
            model_name='fees',
            name='name',
        ),
    ]
